version: '3.8'
services:
  mysql:
    container_name: mysql-bookstore
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users_db
    volumes:
      - "./datasources/mysql/users_db/scripts/01_create_table_users.sql:/docker-entrypoint-initdb.d/1.sql"
